<div class="row">
	<div class="col-md-4"></div>
	<div class="col-md-4">
		<div class="row">
			<div class="col-md-6"><h1>Estados</h1></div>
			<div class="col-md-6">
				<br>
				<?php echo Html::link('estado/nuevo',"Agregar uno","class='btn btn-success'") ?>
				<?php echo Html::link('',"Productos","class='btn btn-success'") ?>
			</div>
		</div>
		
		<?php View::content() ?>
		<table class="table table-striped">
			<thead>
				<th>#</th>
				<th>Estado</th>
				<th></th>
			</thead>
			<?php if (empty($estados)): ?>
				<tr>
					<td colspan="3" style="text-align:center">Sin estados</td>
				</tr>
			<?php else: ?>
				<?php foreach ($estados as $key => $value): ?>
					<tr style="background-color: <?php echo $value->color ?>">
						<td><?php echo $value->id ?></td>
						<td><?php echo $value->nombre ?></td>
						<td><?php echo Html::link("estado/editar/{$value->id}","Editar","class='btn btn-info'") ?></td>
					</tr>
				<?php endforeach ?>
			<?php endif ?>
		</table>
	</div>
	<div class="col-md-4"></div>
</div>