<link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>/jquery-ui-1.11.4/jquery-ui.min.css">
<script type="text/javascript" src="<?php echo PUBLIC_PATH ?>/jquery-ui-1.11.4/jquery-ui.min.js"></script>
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <center><h2>Formulario</h2>
        <?php View::content() ?>
        <?php echo Html::img("spin.gif","Cargando...","class='cargar hide'") ?>
        </center>
        <?php echo Form::open("","post","autocomplete='off'") ?>
        <div class="form-group">
            <p class="alert alert-info">Ingrese algun codigo y a continuacion coloque el cursor en la casilla de nombre de producto, para desplegar las coincidencias *</p>
            <label for="">Productos *</label>
            <input type="text" class="form-control" name="productos_espera[producto]" id="codigo-producto" placeholder="Codigo de producto">
            <?php echo Form::text("productos_espera.nombre_producto","class='form-control' required placeholder='Nombre del producto' ") ?>
        </div>
        <div class="form-group">
            <label for="">Almacen *</label>
            <?php echo Form::select("productos_espera.sucursal",$almacenes,"class='form-control' required") ?>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">Nombre del Cliente *</label>
                    <?php echo Form::text("productos_espera.cliente","class='form-control' required") ?>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">Teléfono *</label>
                    <?php echo Form::text("productos_espera.telefono","class='form-control' required") ?>
                </div>  
            </div>
        </div>
        <div class="form-group">
            <label for="">Observacion</label>
            <?php echo Form::textarea("productos_espera.observacion","class='form-control'") ?>
        </div>
        <?php echo Form::hidden("productos_espera.fecha",NULL,date("Y-m-d H:i:s")) ?>
        <?php echo Form::submit("Guardar","class='btn btn-success'") ?>
        <?php echo Html::link("index/lista","Lista de Productos","class='btn btn-success'") ?>
        <?php echo Form::close() ?>
    </div>
    <div class="col-md-4"></div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        $("#codigo-producto").keyup(function(){
            var valor = $(this).val();
            cargando(true)
            if (valor) {
                $.ajax({
                    url:"index/buscar_por_codigo_producto/"+valor,
                    success:function(r){
                        cargando(false)

                        if (r.length) {
                            resultados = [];
                            for (var i = 0; i < r.length; i++) {
                                resultados.push({label:r[i].description,id:r[i].stockid})
                            }
                            $( "#productos_espera_nombre_producto" ).autocomplete({
                                minLength: 0,
                                source: resultados
                                ,
                                select:function(event, selected){
                                    console.log(selected)
                                    //$("#codigo-producto").val(b.item.value)
                                    $("#productos_espera_nombre_producto").val(selected.item.label)
                                    $("#codigo-producto").val(selected.item.id)
                                }
                            }).on("focus", function () {
                                $(this).autocomplete("search", "");
                            });

                        }
                    }
                })

            }
        });
    })
    function cargando(boleano){
        if (boleano) {
            $(".cargar").removeClass("hide")
        }else{
            $(".cargar").addClass("hide")

        }
    }
</script>