<link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>/jquery-ui-1.11.4/jquery-ui.min.css">
<script type="text/javascript" src="<?php echo PUBLIC_PATH ?>/jquery-ui-1.11.4/jquery-ui.min.js"></script>
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <center><h2>Formulario</h2>
        <?php View::content() ?>
        <?php echo Html::img("spin.gif","Cargando...","class='cargar hide'") ?>
        </center>
        <?php echo Form::open("","post","autocomplete='off'") ?>
        <div class="form-group">
            <p class="alert alert-info">Para realizar la demanda de algun producto específico por parte de alguno de nuestros clientes, busque el producto y rellene el formulario</p>
            <label for="">Productos *</label>
            <div class="row">
                <div class="col-md-6">
                    <input type="text" class="form-control" name="productos_espera[producto]" id="codigo-producto" placeholder="Codigo de producto">
                </div>
                <div class="col-md-6">
                    <button class="btn btn-success" id="btn_buscar">Buscar</button>
                </div>
            </div>
            
            <?php echo Form::text("productos_espera.nombre_producto","class='form-control' readonly required placeholder='Nombre del producto' ") ?>
        </div>
        <div class="form-group">
            <label for="">Almacen *</label>
            <?php echo Form::select("productos_espera.sucursal",$almacenes,"class='form-control' required") ?>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">Nombre del Cliente *</label>
                    <?php echo Form::text("productos_espera.cliente","class='form-control' required") ?>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">Teléfono *</label>
                    <?php echo Form::text("productos_espera.telefono","class='form-control' required") ?>
                </div>  
            </div>
        </div>
        <div class="form-group">
            <label for="">Observacion</label>
            <?php echo Form::textarea("productos_espera.observacion","class='form-control'") ?>
        </div>
        <?php echo Form::hidden("productos_espera.estado_id",NULL,$estados[0]->id) ?>
        <?php echo Form::hidden("productos_espera.fecha",NULL,date("Y-m-d H:i:s")) ?>
        <?php echo Form::submit("Guardar","class='btn btn-success btn_submit'") ?>
        <?php echo Form::reset('Borrar Campos',"class='btn btn-default'") ?>
        <!-- <?php //echo Html::link("index/lista","Lista de Productos","class='btn btn-success'") ?> -->
        <?php echo Form::close() ?>
    </div>
    <div class="col-md-4"></div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        $("#btn_buscar").click(function(){
            var valor = $("#codigo-producto").val();
            cargando(true)
            if (valor) {
                $.ajax({
                    url:"index/buscar_por_codigo_producto/"+valor,
                    success:function(r){
                        cargando(false)

                        if (r.length) {
                            alert("El Producto fue encontrado con exito")
                            //alert(r[0].description)
                            $("#productos_espera_nombre_producto").val(r[0].description)
                            $(".btn_submit").prop("disabled",false)

                        }else{
                            $("#productos_espera_nombre_producto").val("")

                            alert("El producto no existe!");
                            $(".btn_submit").prop("disabled",true)
                        }
                    }
                })

            }
            return false;
        });

    })
    function cargando(boleano){
        if (boleano) {
            $(".cargar").removeClass("hide")
        }else{
            $(".cargar").addClass("hide")

        }
    }
</script>